# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Chasm
                                 A QGIS plugin
 chasm 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-10-12
        copyright            : (C) 2025 by eduardo oliveira
        email                : eduardo7660@univali.br
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Chasm class from file Chasm.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .chasm_calculator import Chasm
    return Chasm(iface)
