# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Chasm
                                 A QGIS plugin
 chasm
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-10-12
        git sha              : $Format:%H$
        copyright            : (C) 2025 by eduardo oliveira
        email                : eduardo7660@univali.br
 ***************************************************************************/

This program is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License, version 2 or later.
"""
import os

from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QMessageBox

from qgis.core import (
    QgsVectorLayer,
    QgsProject,
    QgsMessageLog,
    Qgis,
)

# resources (ícones)
from .resources import *
# diálogo
from .chasm_calculator_dialog import ChasmDialog


class Chasm:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: QgsInterface
        """
        self.iface = iface
        self.plugin_dir = os.path.dirname(__file__)

        # locale
        try:
            locale = (QSettings().value('locale/userLocale') or '')[0:2]
        except Exception:
            locale = ''
        locale_path = os.path.join(self.plugin_dir, 'i18n', f'Chasm_{locale}.qm')
        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # attrs
        self.actions = []
        self.menu = self.tr(u'&Chasm Calculator')
        self.first_start = None
        self.dlg = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Qt translation."""
        return QCoreApplication.translate('Chasm', message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None
    ):
        """Add a toolbar/menu action."""
        action = QAction(QIcon(icon_path), text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)
        if status_tip:
            action.setStatusTip(status_tip)
        if whats_this:
            action.setWhatsThis(whats_this)
        if add_to_toolbar:
            self.iface.addToolBarIcon(action)
        if add_to_menu:
            self.iface.addPluginToMenu(self.menu, action)
        self.actions.append(action)
        return action

    def initGui(self):
        """Create menu/toolbar entries."""
        # ATENÇÃO: o prefix do resources.qrc precisa ser /plugins/chasm_calculator
        icon_path = ':/plugins/chasm_calculator/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Chasm Calculator'),
            callback=self.run,
            parent=self.iface.mainWindow()
        )
        self.first_start = True

    def unload(self):
        """Remove menu/toolbar entries."""
        for action in self.actions:
            self.iface.removePluginMenu(self.tr(u'&Chasm Calculator'), action)
            self.iface.removeToolBarIcon(action)

    # ---------------------------------------------------------------------
    # RUN
    # ---------------------------------------------------------------------
    def run(self):
        """Abre o diálogo, carrega SHP do ZIP e recolhe parâmetros do sDNA."""
        if self.first_start is True or self.dlg is None:
            self.first_start = False
            self.dlg = ChasmDialog(self.iface.mainWindow())

        # mostra o diálogo
        self.dlg.show()
        result = self.dlg.exec_()
        if not result:
            return  # cancelado

        # ---------- 1) Carregar SHP de dentro do ZIP ----------
        zip_path = self.dlg.selected_zip()
        shp_inside = self.dlg.selected_shp1()

        if not zip_path:
            QMessageBox.warning(self.iface.mainWindow(), "Chasm", "Selecione um arquivo .zip.")
            return
        if not os.path.isfile(zip_path):
            QMessageBox.warning(self.iface.mainWindow(), "Chasm", "Arquivo .zip inválido ou inexistente.")
            return
        if not shp_inside:
            QMessageBox.warning(self.iface.mainWindow(), "Chasm", "Selecione um shapefile dentro do .zip.")
            return

        # Normaliza barras no Windows para o GDAL (/vsizip aceita '/')
        norm_zip = os.path.normpath(zip_path).replace('\\', '/')
        vsi_path = f"/vsizip/{norm_zip}/{shp_inside}"
        layer_name = os.path.splitext(os.path.basename(shp_inside))[0]

        vlayer = QgsVectorLayer(vsi_path, layer_name, "ogr")
        if not vlayer or not vlayer.isValid():
            QgsMessageLog.logMessage(f"Falha ao carregar layer: {vsi_path}", "Chasm", Qgis.Critical)
            QMessageBox.critical(self.iface.mainWindow(), "Chasm", "Não foi possível carregar o shapefile do .zip.")
            return

        # evita duplicar: se já existe mesma fonte+nome, não adiciona
        add_layer = True
        for lyr in QgsProject.instance().mapLayers().values():
            try:
                if lyr.source() == vlayer.source() and lyr.name() == vlayer.name():
                    add_layer = False
                    break
            except Exception:
                pass

        if add_layer:
            QgsProject.instance().addMapLayer(vlayer)
            QgsMessageLog.logMessage(f"Camada adicionada: {layer_name}", "Chasm", Qgis.Info)

        # ---------- 2) Pegar camada de rede escolhida ----------
        net_layer = self.dlg.selected_network_layer()
        if net_layer is None:
            QMessageBox.warning(self.iface.mainWindow(), "Chasm", "Selecione a camada de sistema viário (linhas).")
            return

        # ---------- 3) Parâmetros do sDNA (do diálogo) ----------
        params = self.dlg.sdna_params()
        QgsMessageLog.logMessage(f"sDNA params: {params}", "Chasm", Qgis.Info)

        # valida 4 destinos
        dest_weights = [w for w in params.get("dest_weights", []) if w]
        if len(dest_weights) != 4:
            QMessageBox.warning(
                self.iface.mainWindow(),
                "Chasm",
                "Preencha os quatro 'Destination weight' (interesse/existente, outros/existente, interesse/NS, outros/NS)."
            )
            return

        # ---------- 4) (Opcional) Execução do sDNA via Processing ----------
        # Esqueleto comentado — deixar preparado para quando quiser ativar:
        #
        # try:
        #     import processing
        #     alg_id = 'sdna:integral'  # ajuste conforme o identificador do seu sDNA
        #
        #     radius_mode = 0 if params["radius_mode"] == "band" else 1
        #     metric = params["metric"]          # 'ANGULAR' | 'EUCLIDEAN' | 'NORMAL'
        #     weighting = params["weighting"]    # 'Link' | 'Node'
        #     betw = params["betweenness"]
        #     betw_bidir = params["betw_bidirectional"]
        #     origin_w = params["origin_weight"] or ''
        #
        #     for i, dw in enumerate(dest_weights, start=1):
        #         out_name = f"{net_layer.name()}_mad_run{i}"
        #         res = processing.run(
        #             alg_id,
        #             {
        #                 'input_polyline_features': net_layer,
        #                 'compute_betweenness': betw,
        #                 'compute_betweenness_bidirectional': betw_bidir,
        #                 'analysis_metric': metric,
        #                 'radius': params["radius"],
        #                 'radius_mode': radius_mode,  # 0=Band, 1=Continuous (exemplo)
        #                 'weighting': weighting,
        #                 'origin_weight': origin_w,
        #                 'destination_weight': dw,
        #                 'output_features': 'TEMPORARY_OUTPUT'
        #             }
        #         )
        #         # opcional: adicionar ao projeto o resultado de cada rodada
        #         if res and res.get('output_features'):
        #             QgsProject.instance().addMapLayer(res['output_features'])
        #
        #     QMessageBox.information(self.iface.mainWindow(), "Chasm", "Análises sDNA concluídas.")
        #     return
        # except Exception as e:
        #     QgsMessageLog.logMessage(f"Falha ao executar sDNA: {e}", "Chasm", Qgis.Critical)
        #     QMessageBox.critical(self.iface.mainWindow(), "Chasm", f"Falha ao executar sDNA: {e}")
        #     return

        # Por enquanto, apenas confirma o fluxo até aqui:
        QMessageBox.information(
            self.iface.mainWindow(),
            "Chasm",
            "Shapefile carregado do ZIP e parâmetros do sDNA coletados.\n"
            "A execução do sDNA via Processing está pronta para ser ativada."
        )
